name: isolate_pool
description: Spawn isolate depends on your system.
version: 1.0.2
homepage: https://github.com/clbpa/isolate_pool
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
